"""Writes the environment that runs the cell host as a standby beside a cell's own services on the same machine.

On the phone there are no containers: the standby (the other cell's services, ADR-027) shares the network with this
cell's own four hosts, so every port must move. Rather than keep a list by hand, this reads every service's own
configuration out of the cell host jar and shifts each port setting and each address of another service by OFFSET
(8100 -> 8200, 8190 -> 8290). Databases point at this cell's copy of the other cell's database, and NATS at the
standby's own NATS, so the two sets of services never hear each other's events.

    python deploy/cells/standby_env.py cell-host.jar --offset 100 --database sprout_b --nats-port 4223 > standby.env

The output is NAME=value lines with no secrets in them; the standby's run script adds the secrets from its own file.
"""
import argparse
import io
import re
import sys
import zipfile

SETTING = re.compile(r'\$\{([A-Z0-9_]+):([^}]*)\}')
PORT = re.compile(r'^(8[0-9]{3})$')
ADDRESS = re.compile(r'^(https?://(?:127\.0\.0\.1|localhost)):(8[0-9]{3})(.*)$')
DATABASE = re.compile(r'^(jdbc:postgresql://)(?:localhost|127\.0\.0\.1):5432/sprout(\?.*)$')
NATS = re.compile(r'^nats://(?:localhost|127\.0\.0\.1):4222$')


def configs(jar):
    """Every .yml inside the services' jars, and the host's own (the gateway's routes)."""
    with zipfile.ZipFile(jar) as host:
        for name in host.namelist():
            if name.endswith('.yml') and name.startswith('BOOT-INF/classes/'):
                yield name, host.read(name).decode('utf-8')
            if re.match(r'BOOT-INF/lib/sprout-[a-z]+-[\d.]+\.jar$', name):
                with zipfile.ZipFile(io.BytesIO(host.read(name))) as svc:
                    for inner in svc.namelist():
                        if inner.endswith('.yml'):
                            yield inner, svc.read(inner).decode('utf-8')


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('jar')
    ap.add_argument('--offset', type=int, default=100)
    ap.add_argument('--database', required=True)
    ap.add_argument('--db-host', default='127.0.0.1')
    ap.add_argument('--db-port', type=int, default=5432)
    ap.add_argument('--nats-port', type=int, required=True)
    a = ap.parse_args()

    out = {}
    for _, text in configs(a.jar):
        for name, default in SETTING.findall(text):
            if PORT.match(default):
                out[name] = str(int(default) + a.offset)
            elif m := ADDRESS.match(default):
                out[name] = f'{m.group(1)}:{int(m.group(2)) + a.offset}{m.group(3)}'
            elif m := DATABASE.match(default):
                out[name] = f'{m.group(1)}{a.db_host}:{a.db_port}/{a.database}{m.group(2)}'
            elif NATS.match(default):
                out[name] = f'nats://127.0.0.1:{a.nats_port}'
    if not out:
        sys.exit('found no settings to move: is this the cell host jar?')
    print(f'# Generated by deploy/cells/standby_env.py: ports +{a.offset}, database {a.database}, NATS {a.nats_port}')
    for name in sorted(out):
        print(f'{name}={out[name]}')


if __name__ == '__main__':
    main()
